# Generated by Django 6.0.7 on 2026-07-31 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='remarks',
            field=models.TextField(blank=True, help_text='Optional remarks about attendance'),
        ),
    ]
